debug=true


[api]
entryPoint = "traefik"
dashboard = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.traefik]
  address = ":8080"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "service.io"
watch = true
